# DQL Commands to Fetch the required details from Database

SELECT 
`DOCTOR_ID`,
`DOCTOR_NAME`, 
`TOTAL_EXPERIENCE`,
`CONSULTING_CHARGE`,
`EDUCATION_DEGREE`,
`SPECIALITY`,
`CONSULTING_TIME`
FROM 
`SAMARTH`.`DOCTOR_RECORD`;